import { createResource, createSignal, For, Show } from 'solid-js';
import { gamePath, request } from '../api/client';
import type { Calendar, EventDetail, Fixture, News, Receipt, Season, View, WorldStories } from '../api/types';
const status=(s:string)=>({future:'未赛',active:'进行中',completed:'已结束',cancelled:'已取消',pending:'未赛',bye:'轮空',scheduled:'已排定'}[s]||s);
function Empty(props:{children:unknown}){return <div class="empty">{props.children as string}</div>}
function Heading(props:{title:string;subtitle:string}){return <div class="page-heading"><h1 id="page-title" tabIndex={-1}>{props.title}</h1><p>{props.subtitle}</p></div>}
function Fixtures(props:{fixtures:Fixture[];name:(id:number)=>string}){return <div class="fixture-list"><For each={props.fixtures}>{f=><div class="fixture-row"><span class="minor">{f.best_of?`BO${f.best_of}`:'—'}</span><strong>{props.name(f.team_a)}</strong><span class="score">{f.result?.score?`${f.result.score.team_a_score} : ${f.result.score.team_b_score}`:status(f.status)}</span><strong>{f.status==='bye'?'轮空':props.name(f.team_b)}</strong></div>}</For></div>}
export function SchedulePage(props:{game:number;revision:number;view?:View}){
 const [calendar]=createResource(()=>`${props.game}:${props.revision}`,()=>request<Calendar>(gamePath(props.game,'calendar')));const [selected,setSelected]=createSignal('');
 const [detail]=createResource(()=>selected()||false,name=>request<EventDetail>(gamePath(props.game,`events/${encodeURIComponent(name)}`)));
 const name=(id:number)=>props.view?.world.teams.find(t=>t.id===id)?.name||`队伍 #${id}`;
 return <><Heading title="比赛，有自己的日历。" subtitle="正式赛程 / 已确认的参赛记录与对阵"/><Show when={calendar.error}><div class="alert">{calendar.error?.message}</div></Show><Show when={calendar.loading}><Empty>正在读取赛历…</Empty></Show><Show when={calendar()}>{c=><><div class="list-heading"><h2>我的赛程</h2><span>{c().year} SEASON</span></div><Show when={c().player_events.length} fallback={<Empty>当前没有已确认的参赛赛事。年度计划不代表战队已获得参赛资格。</Empty>}><For each={c().player_events}>{row=><section class="event-block"><button class="event-heading" onClick={()=>setSelected(selected()===row.event.name?'':row.event.name)}><span class="date-label">{row.event.date}</span><strong>{row.event.name}</strong><span>{status(row.status)} ↗</span></button><Fixtures fixtures={row.fixtures} name={name}/></section>}</For></Show><Show when={selected()}><div class="event-detail"><div class="list-heading"><h2>{selected()}</h2><button class="text-button" onClick={()=>setSelected('')}>收起</button></div><Show when={detail.error}><p role="alert">{detail.error?.message}</p></Show><Show when={detail()}>{d=><><p>{d().date} · {status(d().status)}</p><p>{d().emptiness_reason}</p><div class="roster-tags"><For each={d().teams}>{t=><span>{t.name}</span>}</For></div></>}</Show></div></Show><details class="calendar-plan"><summary>查看年度赛事计划 · 尚未确认参赛</summary><For each={c().plan}>{event=><div class="compact-row"><time>{event.date}</time><span>{event.name}</span><span class="minor">{event.tier}</span></div>}</For></details></>}</Show></>
}
export function TeamPage(props:{view?:View}){return <><Heading title={props.view?.world.team?.name||'战队'} subtitle="阵容中的每个人，都是你故事的一部分。"/><Show when={props.view?.world.team} fallback={<Empty>目前没有所属战队。</Empty>}>{t=><><div class="team-banner"><div class="team-monogram">{t().name.slice(0,2).toUpperCase()}</div><div><div class="eyebrow">CURRENT ROSTER</div><h2>{t().name}</h2></div><div class="team-rank"><span>世界排名</span><strong>#{t().vrs_ranking}</strong></div></div><div class="list-heading"><h2>当前阵容</h2><span>TEAM SHEET</span></div><div class="table-wrap"><table><thead><tr><th>选手</th><th>定位</th><th>年龄</th><th>士气</th></tr></thead><tbody><For each={props.view?.world.players}>{p=><tr><td><strong>{p.name}</strong>{p.career&&<span class="you-label">你</span>}</td><td>{p.role}</td><td>{p.age}</td><td>{p.pro.morale}</td></tr>}</For></tbody></table></div><div class="team-context"><h2>共同的状态</h2><dl class="facts"><div><dt>队伍凝聚力</dt><dd>{t().chemistry.cohesion.toFixed(1)}</dd></div><div><dt>VRS 积分</dt><dd>{t().vrs_value}</dd></div></dl><p>这些数值来自当前世界状态。人物关系与职业选择会在生涯场景中展开。</p></div></>}</Show></>}
export function WorldPage(props:{game:number;revision:number;view?:View}){
 const [stories]=createResource(()=>`${props.game}:${props.revision}`,()=>request<WorldStories>(gamePath(props.game,'world')));const [news]=createResource(()=>`${props.game}:${props.revision}`,()=>request<News>(gamePath(props.game,'news')));
 return <><Heading title="世界不会只等着你。" subtitle="赛事、对手与竞争格局 / 从模拟世界读取"/><div class="world-columns"><section><div class="list-heading"><h2>赛场快讯</h2><span>RESULTS WIRE</span></div><Show when={news.error}><p class="alert">{news.error?.message}</p></Show><Show when={news()?.items.length} fallback={<Empty>{news.loading?'正在读取赛果…':'尚无顶级赛事赛果。比赛结束后，快讯会在这里出现。'}</Empty>}><For each={news()?.items}>{item=><article class="news-item"><div class="minor">{item.date} · {item.event_name}</div><div class="result-line"><strong>{item.winner}</strong><b>{item.score}</b><span>{item.loser}</span></div></article>}</For></Show><div class="list-heading"><h2>战队观察</h2><span>AROUND THE WORLD</span></div><Show when={stories.error}><p class="alert">{stories.error?.message}</p></Show><For each={stories()?.stories}>{story=><details class="world-story"><summary><span class="minor">#{story.vrs_ranking} · {story.team_name}</span><strong>{story.headline}</strong><span class="read-arrow">↗</span></summary><div class="story-body"><For each={story.body.split('\n').filter(Boolean)}>{line=><p>{line}</p>}</For></div></details>}</For><Show when={!stories.loading&&!stories.error&&!stories()?.stories.length}><Empty>暂无球队动态。</Empty></Show></section><section class="ranking"><div class="list-heading"><h2>世界排名</h2><span>VRS</span></div><For each={[...(props.view?.world.teams||[])].sort((a,b)=>a.vrs_ranking-b.vrs_ranking).slice(0,20)}>{t=><div class="ranking-row"><span>{String(t.vrs_ranking).padStart(2,'0')}</span><strong>{t.name}</strong></div>}</For></section></div></>
}
export function ArchivePage(props:{game:number;revision:number}){
 const [archive]=createResource(()=>`${props.game}:${props.revision}`,()=>request<{archive:Season[]}>(gamePath(props.game,'archive')));const [history]=createResource(()=>`${props.game}:${props.revision}`,()=>request<{items:Receipt[]}>(gamePath(props.game,'career/history')));
 return <><Heading title="走过的路，会留下来。" subtitle="你的决定与赛季记录 / 生涯档案"/><div class="list-heading"><h2>做过的决定</h2><span>YOUR DECISIONS</span></div><Show when={history.error}><p class="alert">{history.error?.message}</p></Show><Show when={history()?.items.length} fallback={<Empty>还没有已记录的故事选择。</Empty>}><For each={history()?.items}>{(item,index)=><article class="history-entry"><span class="history-index">{String(index()+1).padStart(2,'0')}</span><div><h3>一次已经作出的选择</h3><For each={item.outcome.immediate}>{line=><p>{line}</p>}</For><For each={item.outcome.tracking}>{line=><p class="minor">后续追踪：{line}</p>}</For></div></article>}</For></Show><div class="list-heading"><h2>赛季履历</h2><span>SEASON ARCHIVE</span></div><Show when={archive.error}><p class="alert">{archive.error?.message}</p></Show><Show when={archive()?.archive.length} fallback={<Empty>第一个赛季尚未结算。赛季结束后会留下完整履历。</Empty>}><For each={archive()?.archive}>{season=><section class="season-record"><div class="season-year">{season.year}</div><h3>{season.team_name||'自由身'}</h3><p>{season.maps_played} 张地图 · {season.wins} 场胜利 · Rating {season.rating.toFixed(2)}</p><For each={season.honours}>{honour=><p>{honour}</p>}</For></section>}</For></Show></>
}
export function SettingsPage(props:{game:number;font:number;setFont:(n:number)=>void;motion:boolean;setMotion:(v:boolean)=>void;onLoaded:()=>void;onLeave:()=>void}){
 const [state,setState]=createSignal('');const [busy,setBusy]=createSignal(false);const [file,setFile]=createSignal<File>();
 async function load(){if(!file()||busy())return;setBusy(true);setState('正在读取存档…');try{const text=await file()!.text();const body:unknown=JSON.parse(text);await request(gamePath(props.game,'load'),body);props.onLoaded();setState('存档已载入，已清除旧的选择草稿。');setFile(undefined)}catch(e){setState(e instanceof Error?e.message:'读取失败，当前生涯保留')}finally{setBusy(false)}}
 return <><Heading title="按照你的节奏。" subtitle="阅读偏好与生涯保存"/><section class="settings-section"><h2>阅读体验</h2><label class="setting-row"><span>故事正文字号<strong>{props.font}px</strong></span><input type="range" min="17" max="36" step="1" value={props.font} onInput={e=>props.setFont(Number(e.currentTarget.value))}/></label><label class="setting-row check-setting"><span>减少界面动效</span><input type="checkbox" checked={props.motion} onChange={e=>props.setMotion(e.currentTarget.checked)}/></label><p class="minor">显示偏好只保存在这台设备，不改变游戏世界。</p></section><section class="settings-section"><h2>保存与恢复</h2><p>下载当前生涯的完整 JSON 存档，之后可在此恢复。</p><a class="button" href={gamePath(props.game,'save')} download={`csc-career-${props.game}.json`}>下载当前存档 ↓</a><div class="import-save"><label>选择 JSON 存档<input type="file" accept=".json,application/json" onChange={e=>{setFile(e.currentTarget.files?.[0]);setState('')}}/></label><Show when={file()}><p>即将用「{file()?.name}」替换当前生涯。建议先下载当前存档。</p><button disabled={busy()} onClick={()=>void load()}>确认载入此存档</button></Show><p role="status">{state()}</p></div></section><section class="settings-section"><h2>当前连接</h2><p>生涯编号：{props.game}</p><p class="minor">切换入口不会删除服务器上的生涯或存档。</p><button onClick={props.onLeave}>返回生涯选择</button></section></>
}
