import { createEffect, createMemo, createResource, createSignal, For, onCleanup, Show, Switch, Match } from 'solid-js';
import { ApiError, gamePath, request } from '../api/client';
import type { Career, Receipt, View } from '../api/types';
import { ArchivePage, SchedulePage, SettingsPage, TeamPage, WorldPage } from '../features/Pages';

const pages=[['career','生涯','01'],['schedule','赛程','02'],['team','战队','03'],['world','世界','04'],['archive','档案','05'],['settings','设置','06']];
const readPage=()=>pages.some(p=>p[0]===location.hash.slice(1))?location.hash.slice(1):'career';
export default function App(){
 const [page,setPage]=createSignal(readPage());
 const [game,setGame]=createSignal<number|undefined>(localStorage.getItem('csc-game')===null?undefined:Number(localStorage.getItem('csc-game')));
 const [revision,setRevision]=createSignal(0);const refresh=()=>setRevision(v=>v+1);
 const [error,setError]=createSignal('');const [working,setWorking]=createSignal(false);const [connection,setConnection]=createSignal('连接中');
 const [selection,setSelection]=createSignal('');const [receipt,setReceipt]=createSignal<Receipt>();
 const [font,setFont]=createSignal(Number(localStorage.getItem('csc-font'))||18);const [motion,setMotion]=createSignal(localStorage.getItem('csc-motion')==='true');
 let pendingRequest:{scene:string;choice:string;id:string;generation:string}|undefined;
 const [career,{refetch:refetchCareer}]=createResource(()=>game()!==undefined?`${game()}:${revision()}`:false,async()=>request<Career>(gamePath(game()!,'career')));
 const [view]=createResource(()=>game()!==undefined?`${game()}:${revision()}`:false,async()=>request<View>(gamePath(game()!,'view')));
 const currentView=createMemo(()=>career()?.view||view());const player=createMemo(()=>currentView()?.world.players.find(p=>p.career&&!p.retired));
 const scene=createMemo(()=>career()?.scene);const routeChanged=()=>{setPage(readPage());requestAnimationFrame(()=>document.querySelector<HTMLElement>('#page-title')?.focus())};
 window.addEventListener('hashchange',routeChanged);onCleanup(()=>window.removeEventListener('hashchange',routeChanged));
 createEffect(()=>{localStorage.setItem('csc-font',String(font()));document.documentElement.style.setProperty('--reader-size',`${font()}px`);localStorage.setItem('csc-motion',String(motion()));document.documentElement.dataset.reduced=String(motion())});
 createEffect(()=>{const id=game();if(id===undefined)return;let stopped=false;let retries=0;let timer:ReturnType<typeof setTimeout>;let socket:WebSocket;let refreshTimer:ReturnType<typeof setTimeout>;
  const connect=()=>{socket=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/games/${id}/ws`);socket.onopen=()=>{setConnection('已连接');retries=0;refresh()};socket.onmessage=()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,200)};socket.onerror=()=>setConnection('连接中断');socket.onclose=()=>{if(stopped)return;setConnection('连接中断 · 可手动刷新');if(retries<5)timer=setTimeout(connect,Math.min(1000*2**retries++,15000))}};connect();onCleanup(()=>{stopped=true;clearTimeout(timer);clearTimeout(refreshTimer);socket?.close()});
 });
 createEffect(()=>{const id=scene()?.instance_id; if(pendingRequest&&pendingRequest.scene!==id){pendingRequest=undefined;setSelection('')}});
 async function action(fn:()=>Promise<void>){setError('');setWorking(true);try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e));if(e instanceof ApiError&&e.status===409)refresh()}finally{setWorking(false)}}
 function selectChoice(id:string){setSelection(id);if(pendingRequest?.choice!==id)pendingRequest=undefined}
 async function choose(){const current=scene();if(!current||!selection()||working())return;await action(async()=>{
  pendingRequest??={scene:current.instance_id,choice:selection(),id:crypto.randomUUID(),generation:career()!.generation};
  const result=await request<Receipt>(gamePath(game()!,'career/choices'),{request_id:pendingRequest.id,generation:pendingRequest.generation,scene_instance_id:pendingRequest.scene,choice_id:pendingRequest.choice});setReceipt(result);pendingRequest=undefined;setSelection('');refresh();
 })}
 async function proceed(){await action(async()=>{await request<Career>(gamePath(game()!,'career/continue'),{});setReceipt(undefined);setSelection('');refresh()})}
 const shortcuts=(e:KeyboardEvent)=>{if(page()!=='career'||working()||receipt()||(e.target instanceof HTMLElement&&['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)))return;const index=Number(e.key)-1;if(index>=0&&index<3&&scene()?.choices[index])selectChoice(scene()!.choices[index].id)};
 window.addEventListener('keydown',shortcuts);onCleanup(()=>window.removeEventListener('keydown',shortcuts));
 let nameInput!:HTMLInputElement;let roleInput!:HTMLSelectElement;let gameInput!:HTMLInputElement;
 const join=(id:number)=>{setGame(id);localStorage.setItem('csc-game',String(id));setReceipt(undefined);setSelection('');pendingRequest=undefined;location.hash='career'};
 return <><a class="skip-link" href="#content">跳到正文</a><header class="topbar"><a class="brand" href="#career"><span class="brand-mark">C<span>／</span>S</span><span>CAREER SIMULATION<small>职业生涯 · 每一次选择，都留下痕迹</small></span></a><div class="top-context"><span>{currentView()?.date||'你的故事，尚未开始'}</span><span class="connection">{game()!==undefined?connection():'未建立生涯'}</span></div></header>
 <div class="shell"><nav class="sidebar" aria-label="主导航"><div class="nav-caption">THE CAREER</div><For each={pages}>{p=><a href={`#${p[0]}`} classList={{active:page()===p[0]}} aria-current={page()===p[0]?'page':undefined}><span>{p[2]}</span>{p[1]}<span class="nav-arrow">↗</span></a>}</For><div class="nav-foot">COUNTER-STRIKE<br/>从阵容中的一个名字，<br/>到属于自己的职业轨迹。</div></nav>
 <main id="content" class="main"><div class="section-marker"><span>{pages.find(p=>p[0]===page())?.[2]} / {pages.find(p=>p[0]===page())?.[1]}</span><Show when={game()!==undefined}><button class="text-button" onClick={()=>{setError('');refresh()}}>刷新资料 ↻</button></Show></div>
 <Show when={error()}><div class="alert" role="alert">{error()}</div></Show>
 <Show when={game()!==undefined} fallback={<section class="welcome paper"><div class="eyebrow">PROLOGUE / 序章</div><h1 id="page-title" tabIndex={-1}>先让他们<br/>记住你的名字。</h1><p class="lead">从一支职业战队起步。训练、比赛，以及赛后那些没有写进比分的谈话，将构成你的生涯。</p><form onSubmit={e=>{e.preventDefault();void action(async()=>{const result=await request<{game_id:number}>('/games',{player_name:nameInput.value.trim(),role:roleInput.value,policy:'human',story:true});join(result.game_id)})}}><label>选手昵称<input ref={nameInput} required maxLength={32} placeholder="输入你的比赛昵称" autocomplete="nickname"/></label><label>场上定位<select ref={roleInput}><option value="RIFLER">步枪手 / RIFLER</option><option value="AWP">狙击手 / AWP</option><option value="ENTRY">突破手 / ENTRY</option><option value="IGL">指挥 / IGL</option><option value="SUPPORT">辅助 / SUPPORT</option><option value="LURKER">自由人 / LURKER</option></select></label><button class="primary" disabled={working()}>{working()?'正在建立生涯…':'写下第一章 →'}</button></form><details class="resume"><summary>继续已有生涯</summary><form onSubmit={e=>{e.preventDefault();const id=Number(gameInput.value);void action(async()=>{await request<View>(gamePath(id,'view'));join(id)})}}><label>生涯编号<input ref={gameInput} type="number" min="0" required/></label><button disabled={working()}>读取生涯</button></form></details></section>}>
 <Switch><Match when={page()==='career'}><Show when={!career.loading||career()} fallback={<div class="empty">正在读取你的故事…</div>}><Show when={!career.error} fallback={<div class="empty"><h1 id="page-title" tabIndex={-1}>故事暂时无法读取</h1><p>{career.error?.message}</p><button onClick={()=>void refetchCareer()}>重新连接</button></div>}><Show when={receipt()} fallback={<Show when={scene()} fallback={<section class="paper chapter"><div class="eyebrow">BETWEEN CHAPTERS</div><h1 id="page-title" tabIndex={-1}>下一章，还在酝酿。</h1><p class="lead">当前没有满足条件的新场景。你可以查看赛程、战队与已留下的记录。</p><Show when={!career()?.capabilities.advance_world}><p class="capability-note">世界推进功能尚未完成。生涯暂时停在当前日期，选择与资料可正常查看。</p></Show><button class="primary" disabled={working()} onClick={()=>void proceed()}>检查下一段故事 →</button></section>}>{s=><article class="paper chapter"><div class="eyebrow">{s().chapter_title||'CAREER / 职业生涯'}</div><div class="scene-meta"><span>{s().date}</span><span>{s().location}</span><span>{s().actor_name||s().actor_role}</span></div><h1 id="page-title" tabIndex={-1}>{s().title}</h1><div class="prose"><For each={s().paragraphs}>{p=><p>{p}</p>}</For></div><fieldset class="choices" disabled={working()}><legend>你会怎么回应？</legend><For each={s().choices}>{(choice,index)=><label class="choice" classList={{selected:selection()===choice.id}}><input type="radio" name="story-choice" value={choice.id} checked={selection()===choice.id} onChange={()=>selectChoice(choice.id)}/><span class="choice-number">0{index()+1}</span><span><strong>{choice.label}</strong><Show when={choice.impact_certain}><small>{choice.impact_certain}</small></Show><Show when={choice.impact_possible}><small class="possible">可能：{choice.impact_possible}</small></Show></span></label>}</For></fieldset><div class="choice-footer"><span>先选中，再确认。你的决定不会被自动提交。</span><button class="primary" disabled={!selection()||working()} onClick={()=>void choose()}>{working()?'正在确认结果…':'确认这个选择 →'}</button></div></article>}</Show>}>{r=><section class="paper chapter"><div class="eyebrow">A DECISION REMEMBERED</div><h1 id="page-title" tabIndex={-1}>你的回应，已被记住。</h1><div class="prose"><For each={r().outcome.immediate}>{line=><p>{line}</p>}</For><Show when={!r().outcome.immediate.length}><p>这一决定已经记录在生涯档案中。</p></Show></div><Show when={r().outcome.tracking.length}><div class="promise"><h2>接下来值得留意</h2><For each={r().outcome.tracking}>{line=><p>{line}</p>}</For></div></Show><button class="primary" disabled={working()} onClick={()=>void proceed()}>继续阅读 →</button><Show when={!career()?.capabilities.advance_world}><p class="capability-note">新场景需要满足对应条件；当前版本尚不能推进世界日期。</p></Show></section>}</Show></Show></Show></Match>
 <Match when={page()==='schedule'}><SchedulePage game={game()!} revision={revision()} view={currentView()}/></Match><Match when={page()==='team'}><TeamPage view={currentView()}/></Match><Match when={page()==='world'}><WorldPage game={game()!} revision={revision()} view={currentView()}/></Match><Match when={page()==='archive'}><ArchivePage game={game()!} revision={revision()}/></Match><Match when={page()==='settings'}><SettingsPage game={game()!} font={font()} setFont={setFont} motion={motion()} setMotion={setMotion} onLoaded={()=>{setReceipt(undefined);setSelection('');pendingRequest=undefined;refresh()}} onLeave={()=>{setGame(undefined);localStorage.removeItem('csc-game')}}/></Match></Switch>
 </Show></main><aside class="context-rail"><div class="rail-section"><div class="eyebrow">PLAYER DOSSIER</div><Show when={player()} fallback={<><div class="empty-emblem">—</div><h2>席位，为你留着。</h2><p>创建生涯后，这里会记录你的身份与近况。</p></>}>{p=><><div class="player-monogram">{p().name.slice(0,2).toUpperCase()}</div><h2>{p().name}</h2><p>{p().age} 岁 <span class="dot">·</span> {p().role}</p><div class="team-name">{currentView()?.world.team?.name||'自由选手'}</div><dl class="facts"><div><dt>士气</dt><dd>{p().pro.morale}</dd></div><div><dt>疲劳</dt><dd>{p().fatigue.toFixed(0)}</dd></div><div><dt>本年参赛图数</dt><dd>{currentView()?.season?.maps_all??0}</dd></div></dl></>}</Show></div><div class="rail-section"><div class="eyebrow">ON THE HORIZON</div><Show when={currentView()?.next_milestone} fallback={<><h3>下一场，等待排定</h3><p>只有已确认的赛事，才会出现在这里。</p></>}>{m=><><p class="date-label">{m().date}</p><h3>{m().event_name}</h3><a href="#schedule" class="inline-link">查看赛程 ↗</a></>}</Show></div><div class="rail-note">比分写下结果。<br/>选择决定你如何走到那里。</div></aside></div>
 <nav class="mobile-nav" aria-label="移动导航"><a href="#career">生涯</a><a href="#schedule">赛程</a><a href="#world">世界</a><details><summary>更多</summary><div><a href="#team">战队</a><a href="#archive">档案</a><a href="#settings">设置</a></div></details></nav><div class="sr-only" role="status" aria-live="polite">{working()?'正在提交':error()||''}</div></>
}


