// Real local HTTP/UI smoke. Creates an isolated test career, never deletes other games.
import {writeFile} from 'node:fs/promises';
const tabs=await(await fetch('http://127.0.0.1:9223/json')).json();const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m.result);pending.delete(m.id)}};const cdp=(method,params={})=>new Promise(resolve=>{const i=++id;pending.set(i,resolve);ws.send(JSON.stringify({id:i,method,params}))});const evaluate=async expression=>(await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result?.value;const wait=ms=>new Promise(r=>setTimeout(r,ms));
await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});await evaluate("localStorage.removeItem('csc-game');location.href='http://127.0.0.1:5173/#career'");await wait(500);await cdp('Page.reload');await wait(800);
await evaluate("document.querySelector('input[autocomplete=nickname]').value='Codex UI Check';document.querySelector('.welcome form').requestSubmit()");
let game;for(let i=0;i<40;i++){await wait(500);game=await evaluate("localStorage.getItem('csc-game')");if(game)break}if(!game)throw Error('Create game failed');await wait(1200);
const initial=await evaluate("({title:document.querySelector('h1')?.textContent,radios:document.querySelectorAll('input[type=radio]').length,error:document.querySelector('.alert')?.textContent})");if(!initial.radios)throw Error(JSON.stringify(initial));
const shot=async name=>{const r=await cdp('Page.captureScreenshot',{format:'png'});await writeFile(`../docs/screenshots/career-v1/${name}.png`,Buffer.from(r.data,'base64'))};await shot('scene-1440-game');
await evaluate("document.querySelector('input[type=radio]').click()");
const selected=await evaluate("({selected:document.querySelectorAll('input[type=radio]:checked').length,confirmation:[...document.querySelectorAll('button')].find(b=>b.textContent.includes('确认这个选择')).disabled})");if(selected.selected!==1||selected.confirmation)throw Error('Radio selection failed');
await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('确认这个选择')).click()");await wait(1800);
const result=await evaluate("({title:document.querySelector('h1')?.textContent,text:document.querySelector('.chapter')?.innerText,error:document.querySelector('.alert')?.textContent})");if(!result.title?.includes('已被记住'))throw Error(JSON.stringify(result));await shot('outcome-1440-game');
const save=await fetch(`http://127.0.0.1:8080/games/${game}/save`);const saved=await save.json();if(!save.ok)throw Error(JSON.stringify(saved));
await evaluate("location.hash='world'");await wait(700);await evaluate("location.hash='career'");await wait(700);const preserved=await evaluate("document.querySelector('h1')?.textContent");
const report={game_id:Number(game),initial,selected,result,save:{status:save.status,version:saved.version},result_preserved_after_navigation:preserved===result.title};await writeFile('../docs/screenshots/career-v1/interaction.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));ws.close();
